
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjjycbmxwvngglsxneri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqanljYm14d3ZuZ2dsc3huZXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTExNDQsImV4cCI6MjA1OTM2NzE0NH0.HcdyObX1tFDcca2z-hbS1w6N8UVlvy3BUJR3TwWwD98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
